---
- name: Install NZBGet
  ansible.builtin.package:
    name: nzbget
    state: present
  notify:
    - Restart NZBGet

- name: Configure NZBGet user
  ansible.builtin.lineinfile:
    path: /etc/nzbget.conf
    regexp: "^DaemonUsername"
    line: "DaemonUsername={{ nzbget__username }}"
    owner: "{{ nzbget__username }}"
    group: "{{ nzbget__username }}"
  notify:
    - Restart NZBGet

- name: Create NZBGet systemd unit
  ansible.builtin.template:
    src: nzbget.service.j2
    dest: /etc/systemd/system/nzbget.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart NZBGet

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ item  }}"
    state: present
  with_items: nzbget_additional_packages
